### ISSUE TITLE
Difficulty on Linux

### ISSUE THREAD

**Issue by ZakariaX1** [JerwuQu/ggoled#10]
Hey to start off this is awesome and works perfectly on Windows side of things, however I'm having some issues on Linux side of things. Currently running Ubuntu 24.04.1 LTS and I used the cargo install line provided to get things up and running. The cli command ggoled runs but I seem to have to run it with SUDO to be able to connect to the device but thats probably a Linux thing not much you could do but when I do run with SUDO I get a "No info device found" bail (Found in ggoled_lib/lib.rs file). I cant figure out why that happens though. Heres what I find when poking around:
`lsusb` with only the Steelseries device:
```
Bus 001 Device 003: ID 1038:12e0 SteelSeries ApS Arctis Nova Pro Wireless
```
This shows the correct id's

Adding some debug to line 42 of lib.rs:
```rust
        println!("Connected devices:");
        for device_info in api.device_list() {
            println!("{:?}", device_info);
            println!("Path: {:?}", device_info.path());
            println!("Vendor ID: 0x{:04x}", device_info.vendor_id());
            println!("Product ID: 0x{:04x}", device_info.product_id());
            println!("interface_number: {}", device_info.interface_number());
            println!("Usage Page: 0x{:02x}", device_info.usage_page());
            println!("Usage: 0x{:02x}", device_info.usage());
            println!("Serial Number: {:?}", device_info.serial_number());
            println!("Manufacturer String: {:?}", device_info.manufacturer_string());
            println!("Product String: {:?}", device_info.product_string());
            println!();
        }
```
The relevant output for that is (only includes the Steelseries device):
```
HidDeviceInfo { vendor_id: 4152, product_id: 4832 }
Path: "/dev/hidraw1"
Vendor ID: 0x1038
Product ID: 0x12e0
interface_number: 3
Usage Page: 0x0c
Usage: 0x01
Serial Number: Some("")
Manufacturer String: Some("SteelSeries")
Product String: Some("Arctis Nova Pro Wireless")

HidDeviceInfo { vendor_id: 4152, product_id: 4832 }
Path: "/dev/hidraw2"
Vendor ID: 0x1038
Product ID: 0x12e0
interface_number: 4
Usage Page: 0xffc0
Usage: 0x01
Serial Number: Some("")
Manufacturer String: Some("SteelSeries")
Product String: Some("Arctis Nova Pro Wireless")

HidDeviceInfo { vendor_id: 4152, product_id: 4832 }
Path: "/dev/hidraw2"
Vendor ID: 0x1038
Product ID: 0x12e0
interface_number: 4
Usage Page: 0xff00
Usage: 0x01
Serial Number: Some("")
Manufacturer String: Some("SteelSeries")
Product String: Some("Arctis Nova Pro Wireless")
```

Here we see that the interface number is 3 for the first one and 4 for the latter 2, but the latter two seem to have the same array in the HID report which is weird since we are looking for the info and oled screen. It finds the oled screen just fine but not the info. Any ideas?

Side note can we have an extra functionality to run an mp4 (or other video format) in the anim function that automatically cuts it into frames and resizes? OR that you can provide a DIR with all the frames and sort it on name so it goes by each frame in order like: example_001, example_002, example_003 etc.

**Comment by JerwuQu** [comment]
Hello, thanks for your detailed bug report and your interest in this project!

I'll take a look at the bug on a Linux computer later today because I believe it might have regressed after adding support for device info. It was a bit tricky in general since the devices will show as the same PID/VID, interface numbers, etc. but actually refer to different things.
If you can get the report descriptors of the devices that you showed ([get them like this](https://github.com/JerwuQu/ggoled/blob/6842835132ca745de2658b5a153b09e30592e904/ggoled_lib/src/lib.rs#L72)), that would be useful for me.

---

For running without `sudo`, double check that you followed [the install instructions for linux](https://github.com/JerwuQu/ggoled?tab=readme-ov-file#install). 

---

I won't add ability to play mp4s directly because the complexity in handling video files doesn't really belong in this tool.
You can generate and play a directory of frames using `ffmpeg` like you suggested though: 
```sh
ffmpeg -i YOURVIDEO.mp4 -r 20 frames/%04d.png
ggoled anim -r 20 frames/*
```

Note that it will load all the images at startup to be able to play and loop smoothly.
I should probably add this example to the readme 🤔

**Comment by JerwuQu** [comment]
There was definitely some weirdness going on, and I'm pretty sure it's because there are multiple "devices" with the same interface number on the USB device. On Windows they get separated and need to be opened separately, but on Linux they can get put as the same device and therefore gave the same descriptor when I attempted to compare them.

I think it should be fixed now, so please give it a try 😺

**Comment by ZakariaX1** [comment]
Hey it works now, god I love Github!
Thanks for your willingness to help as well and for this cool project, now I'm one step closer to migrating to linux :P

Glad you were able to figure it out without me having to send the reports, I got completely sidetracked in Uni projects its a real pain. But anyway the features seem to all be working (well at least the ggoled commands, not sure about the info part like how you show the headphone and checkmark in the top left when you connect the headset), ran a bad apple animation on it as well so seems good to go!

I'll have a crack at making a similar Linux tray or transformed into CLI or something so Linux can have a screensaver too as a thank you, gives me a reason to look into Rust as well though no idea when I have time :P

**Comment by JerwuQu** [comment]
Awesome!

The plan was to make the tray application work on linux too. There's not too much work needed since the tray library is linux compatible too, I just haven't spent time on it since I don't use the headset for a linux computer. What features from the app are you looking to use? If it's only time and screensaver it should be easy to port without the tray, too.

I'll close this for now, but feel free to open another issue if you run into anything, or a PR if you get something working!

**Comment by p-rintz** [comment]
> Awesome!
> 
> The plan was to make the tray application work on linux too. There's not too much work needed since the tray library is linux compatible too, I just haven't spent time on it since I don't use the headset for a linux computer. What features from the app are you looking to use? If it's only time and screensaver it should be easy to port without the tray, too.
> 
> I'll close this for now, but feel free to open another issue if you run into anything, or a PR if you get something working!

The thing Im most interested in is definitely the screensaver.

I remember my old (old) Steelseries Pro Headset having massive burn-in issues after a few years, so Id want to stop this from happening with my new headset.

Awesome work nonetheless so far!
